kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - python -m unittest
- name: doubletest
  image: python
  commands:
  - pip install -r requirements.txt
  - python -m unittest
trigger:
  event:
  - push
  ref:
  - refs/pull/**
---
kind: pipeline
name: master

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - python -m unittest
trigger:
  event:
  - push
  branch:
  - master
