#!/usr/bin/env python3

import argparse
import functools
import os
import sys

from git import Repo

job_states = ["queued", "processing", "succeeded", "failed", "unknown"]

def move_job(file, state, next_state):
  pass

def apply_job(file):
  pass

def apply_jobs():
  pass

def make_empty_git_dir(dir_name):
  os.makedirs(dir_name)
  f = open(os.path.join(dir_name, ".gitkeep"), "w+")
  f.close()

def list_job_files(state):
  return list(filter(is_job_file, os.listdir(os.path.join("jobs", state))))

# Checks for any duplicate jobs
# A job is considered a duplicate if it is present in the queued
# directory and one other directory
def duplicate_jobs():
  global job_states
  search_states = filter(lambda x: x != "queued", job_states)
  existing_jobs = set(
    functools.reduce(lambda a,b: a.union(set(list_job_files(b))),
      search_states, set([])))

  queued_jobs = set(list_job_files("queued"))

  return existing_jobs.intersection(queued_jobs)

def is_job_file(file):
  return file.endswith(".yaml")

class Goji(object):
  def __init__(self):
    parser = argparse.ArgumentParser(
             description='Runs one off jobs on Kubernetes',
             usage='''goji <command> [<args>]

   process    Process gitops jobs
   requeue    Requeues a job which is in a failed or unknown state
   init       Scaffold a new jobs directory

''')

    parser.add_argument('command', help='Subcommand to run')
    args = parser.parse_args(sys.argv[1:2])

    if not hasattr(self, args.command):
            print(args.command + ' is not a valid command')
            parser.print_help()
            exit(1)

    getattr(self, args.command)()

  def process(self):
    parser = argparse.ArgumentParser(
               description='''Process all queued jobs and update state of running jobs

  Possible states:
    queued    - Will be run during the next process
    succeeded - The job succeeded
    failed    - The job failed and can be requeued
    unknown   - Job is missing and success/failure cannot be determined
''')
    parser.add_argument('--repository')
    args = parser.parse_args(sys.argv[2:])

    duplicates = duplicate_jobs()
    if bool(duplicates):
      print("Error, found the following duplicate jobs: ", duplicates)
      sys.exit(1)


  def requeue(self):
    pass

  def init(self):
    global job_states

    parser = argparse.ArgumentParser(
               description='''Initialise the jobs directory

  If no repository is provided, scaffolds a new jobs repository
''')

    parser.add_argument('--repository', help="Specifies an existing jobs repository to clone")
    args = parser.parse_args(sys.argv[2:])

    if os.path.exists('jobs'):
      print("jobs directory already exists... skipping")
    elif args.repository:
      os.makedirs("jobs")
      print("Cloning " + args.repository)
      Repo.clone_from(args.repository, "jobs")
      print("Done")
    else:
      print("Scaffolding a jobs repository")
      for d in map(lambda x: os.path.join("jobs", x), job_states):
        make_empty_git_dir(d)
      print('''Done, please run:
  $ cd jobs
  $ git init
  $ git add .
  $ git commit -m 'initial commit'
  $ git remote origin add your-bare-repository
  $ git push origin master''')

if __name__ == '__main__':
  Goji()
