#!/usr/bin/env python3

import argparse
import os
import sys

def move_job(file, state, next_state):
  pass

def apply_job(file):
  pass

def apply_jobs():
  pass

def make_empty_git_dir(dir_name):
  os.makedirs(dir_name)
  f = open(os.path.join(dir_name, ".gitkeep"), "w+")
  f.close()

class Goji(object):
  def __init__(self):
    parser = argparse.ArgumentParser(
             description='Runs one off jobs on Kubernetes',
             usage='''goji <command> [<args>]

   process    Process gitops jobs
   requeue    Requeues a job which is in a failed or unknown state
   init       Scaffold a new jobs directory

''')

    parser.add_argument('command', help='Subcommand to run')
    args = parser.parse_args(sys.argv[1:2])

    if not hasattr(self, args.command):
            print(args.command + ' is not a valid command')
            parser.print_help()
            exit(1)

    getattr(self, args.command)()

  def process(self):
    parser = argparse.ArgumentParser(
               description='''Process all queued jobs and update state of running jobs

  Possible states:
    queued    - Will be run during the next process
    succeeded - The job succeeded
    failed    - The job failed and can be requeued
    unknown   - Job is missing and success/failure cannot be determined
''')
    parser.add_argument('--repository')
    args = parser.parse_args(sys.argv[2:])
    print(args)


  def requeue(self):
    pass

  def init(self):
    if os.path.exists('jobs'):
      exit(1)
    else:
      for d in map(lambda x: os.path.join("jobs", x), ["queued", "succeeded", "failed", "unknown"]):
        make_empty_git_dir(d)

if __name__ == '__main__':
  Goji()
