{{- if .Values.defaultClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: goji
roleRef:
 kind: ClusterRole
 name: goji
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: goji
  namespace: jobs
{{- end -}}
