apiVersion: v1
kind: Secret
metadata:
  name: goji
type: Opaque
data:
{{ if .Values.githubPat }}
  githubPat: {{ .Values.githubPat | b64enc }}
{{ end }}
{{ if .Values.githubWebhookSecret }}
  githubWebhookSecret: {{ .Values.githubWebhookSecret | b64enc }}
{{ end }}
