{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "goji.serviceAccountName" . }}
  labels:
{{ include "goji.labels" . | indent 4 }}
{{- end -}}
